### ISSUE TITLE
Add "disabled" option

### ISSUE THREAD

**Issue by mairatma** [metal/metal-select#1]
There's no way to disable the select through its current API. Let's add an option.

**Comment by fernandosouza** [comment]
@mairatma I will do it. Please, assign this issue to me the option is disabled to me.

**Comment by fernandosouza** [comment]
@mairatma. Do you think it would be cool if the metal-select inherited an attribute disable from metal-component?

**Comment by mairatma** [comment]
I think that adding this to all components could be misleading, as the configuration option would exist but not always do anything. It's best if it only exists when it's actually going to be implemented.

**Comment by mairatma** [comment]
I'm trying to assign this to you but you don't come up as one of the possible assignee options. I'll try to see how to change the repo's settings to fix this.

**Comment by mairatma** [comment]
Done! :D

**Comment by fernandosouza** [comment]
Thx @mairatma

**Comment by mairatma** [comment]
This has been done in https://github.com/metal/metal-select/commit/b9be9eff30b84448196d2e0cbfb72c8ff2672384.
