### ISSUE TITLE
Uncaught ReferenceError and Uncaught TypeError

### ISSUE THREAD

**Issue by antoniorhee** [metal/metal-select#14]
![image](https://user-images.githubusercontent.com/28714860/29327132-f9b59e7c-81a2-11e7-9176-3adb6ed997d3.png)

After I `npm install` and `gulp build`, I get the above console errors when I open the demo in my browser. This same issue occurs in several other Metal components (from what I've seen: alert, modal, drag and drop). I was able to avoid this issue on other components by downgrading Metal dependencies to version ^1.0.0-rc.11. This workaround doesn't work for metal-select, however. 

Would appreciate any help on how to solve this issue. Thanks!

**Comment by jbalsas** [comment]
Hey @antoniorhee, sorry this caught me on vacation and I hadn't seen it. I've submitted https://github.com/metal/metal-select/pull/15 with a build fix.

**Comment by antoniorhee** [comment]
@jbalsas An update: I actually did manage to get the demo working by downgrading metal dependencies, however the issue still remains where demos will not work (or even show) with the current version on the dependencies.

**Comment by jbalsas** [comment]
Hey @antoniorhee, yeah, starting from `metal-incremental-dom@2.13.0` our custom build is not able to properly resolve all the dependencies.

We are moving to default tooling (webpack) and have updated all the examples and boilerplates (`metal-examples` and `metal-generator`), but we're still in the process of updating the modules themselves.

**Comment by jbalsas** [comment]
Fixed in https://github.com/metal/metal-select/pull/15
