### ISSUE TITLE
When changes items selectedIndex should reset to 0

### ISSUE THREAD

**Issue by eduardolundgren** [metal/metal-select#3]

**Comment by fernandosouza** [comment]
@eduardolundgren. If I understood well whenever the value of the state items change selectedIndex should get its default value. Right?

The default value of the selectedIndex is -1. With this value, the label `'Select'` is shown. But if selectedIndex is `0`, after items change, the first item of the new array of items get selected.

**Comment by mairatma** [comment]
Yes, I think it makes more sense to use the default value, so it should follow this function: https://github.com/metal/metal-select/blob/master/src/Select.js#L236. Basically, it's -1 if there is a label, but 0 if there isn't. Would be best to refactor that function and use it in both places :)

**Comment by eduardolundgren** [comment]
That works.

**Comment by mairatma** [comment]
This has been done [here](https://github.com/metal/metal-select/commit/8707178fb228f393ea4c676d430bec0cec16804e).
