### ISSUE TITLE
Items are mutated on setter causing wrong hybrid rendering

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-select#7]
In https://github.com/metal/metal-select/commit/d7af3d90365c22f1e0a3f1bdd9d1e024448af1e4 we introduced support for html items.

This, however, causes [mutation of the value](https://github.com/metal/metal-select/blob/master/src/Select.js#L169), so any additional calls to `setState` (hybrid rendering, template refresh) will always trigger an `itemsChanged` event that in turn will reset the value of `selectedIndex`.

This can be verified with the following code in the sample demo:

```js
window.select2.items = ['foo', 'bar'];
window.select2.selectedIndex = 1;
console.log(select2.selectedIndex); // 1
window.select2.items = ['foo', 'bar'];
console.log(select2.selectedIndex); // -1
```

**Comment by fernandosouza** [comment]
Sure, @eduardolundgren.

**Comment by brunobasto** [comment]
Hey @jbalsas,

This is indeed an issue, but just pointing out that in your example, because you are giving different instances of the array, it's expected that itemsChanged should fire. See: https://jsfiddle.net/3dehmrzc/

**Comment by fernandosouza** [comment]
@brunobasto.  Even though you pass the same instance `itemsChanged` still fires. See: https://jsfiddle.net/0zc0m82t/1/

**Comment by brunobasto** [comment]
I see 4 issues here:

1. Mutation of the attributes. If I do
`select.items = ['1', '2', '<i>3</i>'],;`
And then
console.log(select.items);
I would get [function, function, function]

2. We are using `Soy.toIncDom` which doesn't allow us to pass the `key` parameter to the `elementOpen` calls. So, they will always get repainted. To me, it's okay that `itemsChanged` get called as long as incdom prevents things from being repainted on the screen.

3. This is the original issue reported. Changing the `items` shouldn't reset the `selectedIndex`, should it? If that's expected, we could try to diff the array to check if it has actually changed.  

4. Passing the same reference of an array to the attribute shouldn't fire a change event.

**Comment by fernandosouza** [comment]
Thx for clarifying those points, @brunobasto. Now it makes sense to me. The point `1` should be what @eduardolundgren mentioned. And the point `3` seems to be the issue reported by @jbalsas.

**Comment by fernandosouza** [comment]
@brunobasto, I think that the fact of items has no key attribute is not a problem in this case, once they will be a child node of a list, not the list itself. The `key` should be in as the `<li>` attribute [here](https://github.com/metal/metal-select/blob/master/src/Select.soy#L30)

**Comment by brunobasto** [comment]
Oh yeah. That is the idea. The key should go into the <li>. The way it is
right now, nodes won't be reused by incdom.

**Comment by fernandosouza** [comment]
@eduardolundgren I have no permission to publish in NPM.

**Comment by eduardolundgren** [comment]
@fernandosouza I added you to NPM, although I have added a question in the commit trying to understand why you guys used `Object.assign`.
